[[redirects]]
  from = "/project/demo-project"
  to = "https://www.google.com"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/project/test-redirect"
  to = "https://www.google.com"
  status = 301
  force = true # COMMENT: ensure that we always redirect